### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by Dini-Adam** [pmagaz/pablomagaz.com#2]
Locally works okay but I'm having difficulties deploying it to github page.

**Comment by pmagaz** [comment]
Hi,

Do you mean a github static page?

KR

**Comment by Dini-Adam** [comment]
Yes i want to deploy it. I tried couple of times but it failed. See picture attached

![Screen Shot 2019-08-29 at 10 31 01 AM](https://user-images.githubusercontent.com/12256599/63928831-36f51c00-ca48-11e9-8727-de8109dcd9c4.png)

**Comment by pmagaz** [comment]
This project is an Isomorphic App (server side rendering) so you need a NodeJs environment to run it. Unless Github changed it recently you can only serve static content  from Github pages.

**Comment by Dini-Adam** [comment]
Okay what are the free nodejs enviroments available that i can use to run it? I tried running it on heroku free plan it failed. See heroku logs

![Screen Shot 2019-08-29 at 2 54 12 PM](https://user-images.githubusercontent.com/12256599/63946391-fb207d80-ca6c-11e9-9441-a051d12d2f47.png)

**Comment by Dini-Adam** [comment]
I'm actually doing this for the first time. I basically have no experience working with it. Thanks

**Comment by pmagaz** [comment]
Heroku looks a much better place :) If you clone the repository and just execute yarn / npm start as you do in your computer what is the output of the console? Your log looks like an Heroku router error not the app itself.

**Comment by Dini-Adam** [comment]
First output of the console after i cloned the repo and executed **npm start**

![Screen Shot 2019-08-29 at 6 24 04 PM](https://user-images.githubusercontent.com/12256599/63962305-84927880-ca8a-11e9-8da4-ba63cc1a60f4.png)

After i installed the node_modules i run  **npm start** and It works okay on local host

![Screen Shot 2019-08-29 at 6 07 42 PM](https://user-images.githubusercontent.com/12256599/63961334-7d6a6b00-ca88-11e9-9ed3-e889be77c2e2.png)

![Screen Shot 2019-08-29 at 6 42 29 PM](https://user-images.githubusercontent.com/12256599/63963472-0388b080-ca8d-11e9-945c-845c8e4b2fbc.png)

So I used the following method to deploy the app - (https://devcenter.heroku.com/articles/deploying-nodejs) 

![Screen Shot 2019-08-29 at 6 47 46 PM](https://user-images.githubusercontent.com/12256599/63964307-b60d4300-ca8e-11e9-8281-445ad67e7bcb.png)


![Screen Shot 2019-08-29 at 6 45 41 PM](https://user-images.githubusercontent.com/12256599/63963631-5d897600-ca8d-11e9-8c50-e1b2b4d91388.png)

**Comment by Dini-Adam** [comment]
Procfile **web: node dist/app.js**
So yeah that's actually where i have been stucked.

**Comment by pmagaz** [comment]
If you see server up in localhost:port is because the App is running correctly. You need to configure correctly your Heroku account to redirect request from http://dinisoft.herokuapp.com/ to your internal localhost:8000.

**Comment by Dini-Adam** [comment]
Thank you but i've stumble on another error. 

![Screen Shot 2019-08-31 at 9 51 11 AM](https://user-images.githubusercontent.com/12256599/64061614-29b96800-cbd5-11e9-8237-4a9596746cfa.png)

**Comment by Dini-Adam** [comment]
Thank you i found the solution :)  Heroku assign port dynamically. Now its up and running.
https://stackoverflow.com/questions/15693192/heroku-node-js-error-web-process-failed-to-bind-to-port-within-60-seconds-of

server/httpServer.js

```
import base from 'base/';
import envConf from './enviroment';

const httpServer = app => {
  app.listen(process.env.PORT || 8000, err => {
    if (err) return base.console.error(`${ err }`);
    base.console.success(`HTTP Server up on http://localhost:${ envConf.port }`);
  });
};

export default httpServer;

```
App - http://dinisoft.herokuapp.com
